# The Docker image that will be used to build your app
image: registry.gitlab.com/quarto-forge/docker/polyglot
# Functions that should be executed before the build script is run
before_script:
  - pip install poetry
  - poetry install
  - poetry shell

pages:
  tags:
    - puzl-runner
  script:
    - quarto render --execute --to html --output-dir public
  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      - public
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH

